// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqQIzqXk9IQw26JqHR-VFKg160hgFseU0',
    appId: '1:521570815282:web:7239524aad9bab04615b2b',
    messagingSenderId: '521570815282',
    projectId: 'onex-gas-appliances',
    authDomain: 'onex-gas-appliances.firebaseapp.com',
    storageBucket: 'onex-gas-appliances.firebasestorage.app',
    measurementId: 'G-JG3G1WHQBZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDP98qHJa9xjUsabI5IB4vhnw2TXYclstM',
    appId: '1:521570815282:android:37511c0622ad8fcb615b2b',
    messagingSenderId: '521570815282',
    projectId: 'onex-gas-appliances',
    storageBucket: 'onex-gas-appliances.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvj7RkZBPrgJzKSNzPOb2Zul0NTZ-z-w8',
    appId: '1:521570815282:ios:18da6f6178df3887615b2b',
    messagingSenderId: '521570815282',
    projectId: 'onex-gas-appliances',
    storageBucket: 'onex-gas-appliances.firebasestorage.app',
    iosBundleId: 'com.example.onexGasAppliances',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvj7RkZBPrgJzKSNzPOb2Zul0NTZ-z-w8',
    appId: '1:521570815282:ios:18da6f6178df3887615b2b',
    messagingSenderId: '521570815282',
    projectId: 'onex-gas-appliances',
    storageBucket: 'onex-gas-appliances.firebasestorage.app',
    iosBundleId: 'com.example.onexGasAppliances',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqQIzqXk9IQw26JqHR-VFKg160hgFseU0',
    appId: '1:521570815282:web:878adf0674a54832615b2b',
    messagingSenderId: '521570815282',
    projectId: 'onex-gas-appliances',
    authDomain: 'onex-gas-appliances.firebaseapp.com',
    storageBucket: 'onex-gas-appliances.firebasestorage.app',
    measurementId: 'G-T5Y4ZPRHFJ',
  );

}